/**
 * The Certificate of Authenticity — the document that makes this package usable by a
 * lawyer or a court rather than just persuasive to a platform.
 *
 * Both countries we cover have a route for authenticating electronic records by written
 * certification rather than live testimony:
 *
 *  - **United States.** Federal Rules of Evidence 902(13) and 902(14), in force since
 *    1 December 2017, allow a record generated by an electronic process, or a copy of data
 *    identified by a reliable digital process such as a hash value, to be self-authenticated
 *    by certification. 902(14) is written almost exactly around hash comparison.
 *  - **Canada.** Canada Evidence Act s. 31.1 puts the burden of authentication on the party
 *    presenting an electronic document; s. 31.2 satisfies the best evidence rule on proof of
 *    the integrity of the electronic documents system, and s. 31.3 provides a route to
 *    proving that integrity.
 *
 * This certificate is drafted to that structure. Two things it is careful not to do:
 * it never asserts the *content* is true — only that the file is unchanged and existed by a
 * given time — and it states in its own text that it is a template requiring review, not
 * legal advice. Overstating either would be worse than useless to the person relying on it.
 */
import type { jsPDF } from 'jspdf';
import type { EvidenceRecord } from './types';
import { formatDigestForHumans } from './hash';
import { findCountry } from './jurisdictions';
import { formatDuration } from './media';
import { formatLocation } from './geo';

const PAGE = { width: 595.28, height: 841.89 };
const MARGIN = 62;
const CONTENT_WIDTH = PAGE.width - MARGIN * 2;

const INK: [number, number, number] = [20, 24, 33];
const MUTED: [number, number, number] = [92, 100, 116];

export interface CertificateInput {
  record: EvidenceRecord;
  /** Filename the original evidence will be saved under, so the certificate names it. */
  evidenceFilename: string;
  proofFilename?: string;
}

export async function buildCertificatePdf({
  record,
  evidenceFilename,
  proofFilename,
}: CertificateInput): Promise<Blob> {
  const { jsPDF: JsPDF } = await import('jspdf');
  const pdf = new JsPDF({ unit: 'pt', format: 'a4', compress: true });
  const handover = record.handover;
  const country = handover ? findCountry(handover.countryId) : undefined;

  let y = MARGIN;

  const ensure = (space: number): void => {
    if (y + space > PAGE.height - MARGIN) {
      pdf.addPage();
      y = MARGIN;
    }
  };
  const text = (
    value: string,
    opts: { size?: number; bold?: boolean; muted?: boolean; mono?: boolean; gapAfter?: number } = {},
  ): void => {
    const size = opts.size ?? 10.5;
    pdf.setFont(opts.mono ? 'courier' : 'helvetica', opts.bold ? 'bold' : 'normal').setFontSize(size);
    pdf.setTextColor(...(opts.muted ? MUTED : INK));
    for (const line of pdf.splitTextToSize(value, CONTENT_WIDTH) as string[]) {
      ensure(size + 5);
      pdf.text(line, MARGIN, y);
      y += size + 5;
    }
    y += opts.gapAfter ?? 0;
  };
  const rule = (): void => {
    ensure(16);
    pdf.setDrawColor(210, 216, 224).setLineWidth(0.75);
    pdf.line(MARGIN, y, PAGE.width - MARGIN, y);
    y += 16;
  };
  /** A labelled line with a rule to write on. */
  const signatureLine = (label: string, prefill = ''): void => {
    ensure(46);
    y += 16;
    pdf.setDrawColor(120, 128, 140).setLineWidth(0.9);
    pdf.line(MARGIN, y, MARGIN + 320, y);
    if (prefill) {
      pdf.setFont('helvetica', 'normal').setFontSize(11).setTextColor(...INK);
      pdf.text(prefill, MARGIN + 4, y - 5);
    }
    y += 13;
    pdf.setFont('helvetica', 'normal').setFontSize(8.5).setTextColor(...MUTED);
    pdf.text(label.toUpperCase(), MARGIN, y);
    y += 14;
  };

  // ---- Title --------------------------------------------------------------
  pdf.setFont('helvetica', 'bold').setFontSize(19).setTextColor(...INK);
  pdf.text('Certificate of Authenticity', MARGIN, y);
  y += 22;
  pdf.setFont('helvetica', 'normal').setFontSize(10).setTextColor(...MUTED);
  pdf.text('Electronic record identified by cryptographic hash', MARGIN, y);
  y += 20;
  rule();

  if (country) {
    text(`Prepared with reference to ${country.evidenceLaw.citation}.`, {
      size: 9.5,
      muted: true,
      gapAfter: 6,
    });
  }

  // ---- 1. Declarant -------------------------------------------------------
  text('1. Declarant', { bold: true, size: 12.5, gapAfter: 4 });
  text(
    'I, the undersigned, have personal knowledge of the matters stated in this certificate ' +
      'and am competent to testify to them.',
    { gapAfter: 4 },
  );
  signatureLine('Full name (print)', handover?.declarantName ?? '');
  if (handover?.declarantContact) {
    signatureLine('Contact', handover.declarantContact);
  } else {
    signatureLine('Contact (email or telephone)');
  }
  y += 4;

  // ---- 2. The record ------------------------------------------------------
  text('2. The electronic record', { bold: true, size: 12.5, gapAfter: 4 });
  text(
    `This certificate concerns a single ${record.kind === 'video' ? 'video recording' : 'digital image'} ` +
      `saved as "${evidenceFilename}"` +
      (proofFilename ? `, accompanied by a timestamp proof file saved as "${proofFilename}"` : '') +
      '.',
    { gapAfter: 6 },
  );

  const rows: [string, string][] = [
    ['File name', evidenceFilename],
    ['Media type', record.mimeType],
    ['Size', `${record.byteLength.toLocaleString()} bytes`],
    ['Record identifier', record.id],
    ['Captured', `${new Date(record.capturedAt).toLocaleString()} (${record.timeZone})`],
    ['Captured (ISO 8601)', record.capturedAt],
  ];
  if (record.kind === 'video') {
    rows.push([
      'Duration',
      record.durationSeconds ? formatDuration(record.durationSeconds) : 'Not available',
    ]);
    rows.push([
      'Audio',
      record.source === 'upload'
        ? 'As present in the original file'
        : record.hasAudio
          ? 'Recorded'
          : 'Not recorded',
    ]);
  }
  rows.push([
    'Method of capture',
    record.source === 'live'
      ? 'Captured directly through the application, using the device camera'
      : 'Imported from storage on the device',
  ]);
  if (record.details.location) {
    rows.push(['Location', formatLocation(record.details.location)]);
  }

  for (const [label, value] of rows) {
    ensure(15);
    pdf.setFont('helvetica', 'bold').setFontSize(8.5).setTextColor(...MUTED);
    pdf.text(label.toUpperCase(), MARGIN, y);
    pdf.setFont('helvetica', 'normal').setFontSize(10).setTextColor(...INK);
    const lines = pdf.splitTextToSize(value, CONTENT_WIDTH - 150) as string[];
    lines.forEach((line, i) => {
      if (i > 0) ensure(13);
      pdf.text(line, MARGIN + 150, y);
      if (i < lines.length - 1) y += 13;
    });
    y += 16;
  }
  y += 4;

  // ---- 3. Digital identification -----------------------------------------
  text('3. Process of digital identification', { bold: true, size: 12.5, gapAfter: 4 });
  text(
    'The record was identified by computing a SHA-256 cryptographic hash of its exact bytes. ' +
      'SHA-256 is a published, widely used one-way hash function. Any alteration of the file, ' +
      'however small, produces a different hash value. The hash of the file described above is:',
    { gapAfter: 8 },
  );
  text(formatDigestForHumans(record.digestHex), { mono: true, size: 10.5, gapAfter: 8 });
  text(
    'The hash was computed on the declarant’s own device by the Evidence Vault application, ' +
      'using the Web Crypto API provided by the device’s web browser. The file was not ' +
      'transmitted to any server in order to compute it.',
    { gapAfter: 10 },
  );

  // ---- 4. Timestamp -------------------------------------------------------
  text('4. Proof of existence at a point in time', { bold: true, size: 12.5, gapAfter: 4 });
  if (record.proof) {
    const responded = record.proof.calendars.filter((c) => c.ok).map((c) => c.calendar);
    text(
      `Immediately after the hash was computed, it was submitted to ${responded.length} independent ` +
        'public OpenTimestamps calendar servers. OpenTimestamps is an open standard that aggregates ' +
        'submitted hashes and commits them to a public, append-only blockchain ledger, producing a ' +
        'proof that a given hash existed no later than a given block. No cryptocurrency is ' +
        'purchased, transferred or held in the process; the ledger is used solely as a public ' +
        'record that cannot be altered retrospectively. For the avoidance of doubt in any ' +
        'technical examination, the ledger used by the OpenTimestamps standard is the Bitcoin ' +
        'blockchain. The submission was made at:',
      { gapAfter: 6 },
    );
    text(
      `${new Date(record.proof.submittedAt).toLocaleString()} (${record.timeZone})\n` +
        `ISO 8601: ${record.proof.submittedAt}`,
      { mono: true, size: 9.5, gapAfter: 6 },
    );
    text('Calendar servers that accepted the submission:', { size: 9.5, muted: true, gapAfter: 2 });
    text(responded.join('\n') || 'None', { mono: true, size: 9, gapAfter: 8 });
    text(
      'The accompanying proof file can be verified by any person, using the standard ' +
        'OpenTimestamps client software, without the involvement of the declarant, the authors of ' +
        'the application, or any server under their control.',
      { gapAfter: 10 },
    );
  } else {
    text(
      'No timestamp proof was obtained for this record. The hash above still establishes that the ' +
        'file has not been altered since it was computed, but does not by itself establish the time ' +
        'at which the file existed.',
      { gapAfter: 10 },
    );
  }

  // ---- 5. Statement -------------------------------------------------------
  text('5. Statement', { bold: true, size: 12.5, gapAfter: 4 });
  text('I certify that:', { gapAfter: 4 });
  text(
    '(a)  The file described in paragraph 2 is a true and unaltered copy of the ' +
      `${record.kind === 'video' ? 'recording' : 'image'} as it was captured on the date and time stated;\n\n` +
      '(b)  The hash value stated in paragraph 3 was produced from that file by the process ' +
      'described, and I have compared it to the value recorded in the accompanying report and ' +
      'found them identical;\n\n' +
      '(c)  The file has not been edited, cropped, re-encoded, or otherwise modified since it was ' +
      'captured;\n\n' +
      '(d)  I have not altered, and am not aware of any alteration to, the accompanying proof file.',
    { gapAfter: 10 },
  );

  // ---- 6. Scope -----------------------------------------------------------
  text('6. Scope and limitations of this certificate', { bold: true, size: 12.5, gapAfter: 4 });
  text(
    'This certificate speaks only to the integrity and provenance of a computer file. It does not ' +
      'assert that the content depicted is true, that any person shown or named published it, or ' +
      'that any offence occurred. Those are separate questions requiring separate evidence.',
    { gapAfter: 6 },
  );
  if (record.source === 'upload') {
    text(
      'The file was imported from storage on the device rather than captured through the ' +
        'application. It therefore existed before the application processed it, and this certificate ' +
        'does not speak to its handling before that point.',
      { gapAfter: 6 },
    );
  }
  text(
    'The authors of the Evidence Vault application are not lawyers, provide no legal advice, and ' +
      'make no representation that this certificate satisfies the requirements of any particular ' +
      'court or proceeding. It is a template. It should be reviewed, and where necessary amended, ' +
      'by counsel before it is relied upon.',
    { gapAfter: 6 },
  );
  if (country?.id === 'us') {
    text(
      'Note on procedure: Rule 902 requires the proponent of a self-authenticating record to give ' +
        'an adverse party reasonable written notice of the intent to offer it, and to make the ' +
        'record and certification available for inspection, so that the party has a fair ' +
        'opportunity to challenge them.',
      { size: 9.5, muted: true, gapAfter: 8 },
    );
  }
  if (country?.id === 'ca') {
    text(
      'Note on procedure: under the Canada Evidence Act the party seeking to admit an electronic ' +
        'document bears the burden of proving its authenticity, and may prove the integrity of the ' +
        'electronic documents system by affidavit.',
      { size: 9.5, muted: true, gapAfter: 8 },
    );
  }

  // ---- 7. Signature -------------------------------------------------------
  ensure(150);
  rule();
  text('7. Signature', { bold: true, size: 12.5, gapAfter: 6 });
  text(
    'I declare under penalty of perjury, or under such equivalent affirmation as the law of the ' +
      'relevant jurisdiction provides, that the foregoing is true and correct to the best of my ' +
      'knowledge and belief.',
    { size: 10, gapAfter: 4 },
  );
  signatureLine('Signature');
  signatureLine('Printed name', handover?.declarantName ?? '');
  signatureLine('Date');
  signatureLine('Place (city and jurisdiction)');

  // ---- footer -------------------------------------------------------------
  const total = pdf.getNumberOfPages();
  for (let p = 1; p <= total; p += 1) {
    pdf.setPage(p);
    pdf.setFont('helvetica', 'normal').setFontSize(8).setTextColor(...MUTED);
    pdf.text(`Certificate of authenticity — record ${record.id}`, MARGIN, PAGE.height - 30);
    pdf.text(`Page ${p} of ${total}`, PAGE.width - MARGIN, PAGE.height - 30, { align: 'right' });
  }

  return pdf.output('blob') as Blob;
}

/** Narrow re-export so callers do not need to import jsPDF's types directly. */
export type CertificateDoc = jsPDF;
